/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arbolE;

import java.awt.Image;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author thege
 */
public class Frrameinterfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frrameinterfaz.class.getName());
    
    /**
     * Creates new form Frrameinterfaz
     */
    String nPolaca;
    int temp;
    FrameCuadruplos cuadruplos;
    public void inOrden(Nodo n){
        if(n!=null){
            inOrden(n.getDerecho());
            jTextInOrden.append(n.getDato()+"\n");
            
            inOrden(n.getIzquierdo());
        }
    }
    
    public void preOrden(Nodo n){
        if (n!=null) {
           jTextPreOrden.append(n.getDato()+"\n");
           nPolaca += jNotacionPolaca.getText()+ n.getDato()+" ";
           jNotacionPolaca.setText(jNotacionPolaca.getText()+ n.getDato()+" ");
           
           preOrden(n.getIzquierdo());
           preOrden(n.getDerecho());
 
        }
    }
    
    PanelGrafo panel = new PanelGrafo(
    Arbol.convertirAGAD(arbolExpresion),
    colorNodo,
    radioNodo,
    colorLinea,
    grosorLinea
    );

    ventana.add(panel);
    ventana.setSize(600, 400);
    ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ventana.setLocationRelativeTo(null); // Centrar en pantalla
    ventana.setVisible(true);
    
    public void postOrden(Nodo n){
        if(n!=null){
            postOrden(n.getDerecho());
            postOrden(n.getIzquierdo());
            jTextPostOrden.append(n.getDato()+"\n");
        }
    }
    
    public Frrameinterfaz() {
    initComponents();
    
    // Imagen 1
    ImageIcon icono = new ImageIcon(getClass().getResource("/Imagenes/escudo_itt_grande.png"));
    Image imagen = icono.getImage();
    Image imagenEscalada = imagen.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    jLabel9.setIcon(new ImageIcon(imagenEscalada));

    // Imagen 2
    ImageIcon icono2 = new ImageIcon(getClass().getResource("/Imagenes/personal.png"));
    Image imagen2 = icono2.getImage();
    Image imagenEscalada2 = imagen2.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    jLabel10.setIcon(new ImageIcon(imagenEscalada2));
    

    // Imagen 3
    ImageIcon icono3 = new ImageIcon(getClass().getResource("/Imagenes/logohorafix.png"));
    Image imagen3 = icono3.getImage();
    Image imagenEscalada3 = imagen3.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    jLabel12.setIcon(new ImageIcon(imagenEscalada3));
    }
    
   public void intermedio(Nodo n){
      if(n!=null){
          intermedio(n.getIzquierdo());
          intermedio(n.getDerecho());
          
      if(n.getIzquierdo()==null && n.getDerecho()==null){
          n.setLugar(n.getDato()+" ");
          n.setCodigoIntermedio("");
      }else{
          if(n.getDato().equals("+")|| n.getDato().equals("*")
                  ||n.getDato().equals("-")||n.getDato().equals("/")){
              temp++;
              n.setLugar("T" + temp);
              Nodo izquierdo = n.getIzquierdo();
              Nodo derecho = n.getDerecho();
              String codigoI = "";
              codigoI = izquierdo.getCodigoIntermedio()+ " " + derecho.getCodigoIntermedio() + 
                      " " + n.getLugar()+ "="+izquierdo.getLugar()+
                     "" + n.getDato()+ " " +derecho.getLugar();
              
              n.setCodigoIntermedio(codigoI+"\n");
              
              }else{
                      if(n.getDato().equals("=")){
                      String codigoI= "";
                      Nodo izquierdo = n.getIzquierdo();
                      Nodo derecho = n.getDerecho();
                      codigoI = derecho.getDato()+ " "+
                              izquierdo.getLugar()+ " = "+temp+ "\n";
                      n.setCodigoIntermedio(codigoI);
                      }//EQUALS =
      }//equals +-*/
  }//getDerecho getIzquierdo
  }//n!null
  }//intermedio
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPreOrden = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextInOrden = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPostOrden = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextReglasSemanticas = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextTresDirecciones = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jNotacionPolaca = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arbol de expresiones - LyA2");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ARBOL DE EXPRESIONES - LYA2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(104, 104, 104)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Expresión");

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Compila");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTextPreOrden.setColumns(20);
        jTextPreOrden.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextPreOrden.setRows(5);
        jScrollPane1.setViewportView(jTextPreOrden);

        jTextInOrden.setColumns(20);
        jTextInOrden.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextInOrden.setRows(5);
        jScrollPane2.setViewportView(jTextInOrden);

        jTextPostOrden.setColumns(20);
        jTextPostOrden.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextPostOrden.setRows(5);
        jScrollPane3.setViewportView(jTextPostOrden);

        jTextReglasSemanticas.setColumns(20);
        jTextReglasSemanticas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextReglasSemanticas.setRows(5);
        jScrollPane4.setViewportView(jTextReglasSemanticas);

        jTextTresDirecciones.setColumns(20);
        jTextTresDirecciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextTresDirecciones.setRows(5);
        jScrollPane5.setViewportView(jTextTresDirecciones);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Pre Orden");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("In Orden");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Post Orden");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Reglas Semanticas");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Codigo 3 Direcciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(115, 115, 115)
                .addComponent(jLabel4)
                .addGap(104, 104, 104)
                .addComponent(jLabel5)
                .addGap(179, 179, 179)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Notacion Polaca");

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Codigo 3 Direcciones");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("CLEAN");

        jButton4.setBackground(new java.awt.Color(255, 102, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("TABLA DE SIMBOLOS");

        jButton7.setBackground(new java.awt.Color(255, 102, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("CUADRUPLOS");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jNotacionPolaca, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jNotacionPolaca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addGap(20, 20, 20))
        );

        jButton5.setBackground(new java.awt.Color(255, 102, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Agente IA");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setBackground(new java.awt.Color(255, 102, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("OptimizarCI");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String datos = jTextField1.getText().trim();
 
        if (datos.isEmpty()) {
            jTextReglasSemanticas.setText("⚠ Ingresa una expresión antes de compilar.");
            return;
        }
 
        // CAMBIO: usar ArbolEder en lugar de Arbol
        ArbolGerman a = new ArbolGerman();
        Nodo arbolExpresion = a.crear(datos);
 
        // Limpiar y mostrar reglas semánticas en jTextArea4
        jTextReglasSemanticas.setText("");
        jTextReglasSemanticas.append(a.getReglasEjecutadas());
 
        // Enviar las reglas semanticas generadas a un archivo de texto "reglasSemanticas.txt"
        guardarReglasEnArchivo(a.getReglasEjecutadas());
    }//GEN-LAST:event_jButton1ActionPerformed
    private void guardarReglasEnArchivo(String contenido) {
        String ruta = obtenerRutaEscritorio() + java.io.File.separator + "reglasSemanticas.txt";
        try (java.io.PrintWriter pw = new java.io.PrintWriter(
                new java.io.FileWriter(ruta))) {
            pw.print(contenido);
            System.out.println("Archivo guardado en: " + ruta);
        } catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar reglasSemanticas.txt: " + e.getMessage(),
                    "Error de archivo",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String obtenerRutaEscritorio() {
        String home = System.getProperty("user.home");
        String sep = java.io.File.separator;
        String[] candidatos = {
            home + sep + "Desktop",
            home + sep + "OneDrive" + sep + "Desktop",
            home + sep + "OneDrive" + sep + "Escritorio",
            home + sep + "Escritorio"
        };
        for (String candidato : candidatos) {
            java.io.File carpeta = new java.io.File(candidato);
            if (carpeta.exists() && carpeta.isDirectory()) {
                return candidato;
            }
        }
        // Ninguna carpeta de escritorio encontrada: usar la carpeta de usuario
        return home;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          FrameDescripcion ventanaIntermedio = new FrameDescripcion();
          ventanaIntermedio.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String datos= "";
        
        ArbolAgenteIA arbol = new ArbolAgenteIA();
        datos = jTextField1.getText();
        Nodo arbolExpresiones = arbol.crear(datos);
        jTextReglasSemanticas.append(arbol.getReglasEjecutadas());
        
        JFrame ventana = new JFrame("Visualizardor de Arboles - LyA2");
        PanelArbol panel = new PanelArbol(arbolExpresiones, arbol.tablaSimbolos);  
        
        ventana.add(panel);
        ventana.setSize(600, 400);
        ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        ventana.setLocationRelativeTo(null);//Centrar en pantalla
        ventana.setVisible(true);
        
        preOrden(arbolExpresiones);
        inOrden(arbolExpresiones);
        postOrden(arbolExpresiones);
        
        intermedio(arbolExpresiones);
        jTextTresDirecciones.append(arbolExpresiones.getCodigoIntermedio());

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String urlVideo = "https://youtu.be/90Y3tJh0Pxc"; // <-- reemplaza con tu URL real

    try {
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop.getDesktop().browse(new java.net.URI(urlVideo));
        } else {
            JOptionPane.showMessageDialog(this,
                    "Tu sistema no soporta abrir el navegador automáticamente.",
                    "No soportado",
                    JOptionPane.WARNING_MESSAGE);
        }
    } catch (java.io.IOException | java.net.URISyntaxException e) {
        JOptionPane.showMessageDialog(this,
                "No se pudo abrir el video: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        cuadruplos = new FrameCuadruplos(arbolExpresiones);
        cuadruplos.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed
    /**
     * Recorre el arbol y recolecta los identificadores (hojas que son
     * letras, no operadores) para poder solicitar su valor.
     */
     private void obtenerIdentificadores(Nodo nodo, Set<String> identificadores) {
        if (nodo == null) return;

        boolean esHoja = (nodo.getIzquierdo() == null && nodo.getDerecho() == null);
        String dato = nodo.getDato();
        if (esHoja && dato != null && dato.length() >= 1 && Character.isLetter(dato.charAt(0))) {
            identificadores.add(dato);
        }

        obtenerIdentificadores(nodo.getIzquierdo(), identificadores);
        obtenerIdentificadores(nodo.getDerecho(), identificadores);
    }

    private double evaluarArbol(Nodo nodo, java.util.HashMap<String, String> tabla) {
        if (nodo == null) return 0;

        boolean esHoja = (nodo.getIzquierdo() == null && nodo.getDerecho() == null);
        if (esHoja) {
            String dato = nodo.getDato();
            String valorTexto = tabla.get(dato);
            if (valorTexto != null) {
                try {
                    return Double.parseDouble(valorTexto);
                } catch (NumberFormatException e) {
                    return 0;
                }
            }
            try {
                return Double.parseDouble(dato);
            } catch (NumberFormatException e) {
                return 0;
            }
        }

        double primerOperando  = evaluarArbol(nodo.getDerecho(), tabla);
        double segundoOperando = evaluarArbol(nodo.getIzquierdo(), tabla);
        String operador = nodo.getDato();

        switch (operador) {
            case "+": return primerOperando + segundoOperando;
            case "-": return primerOperando - segundoOperando;
            case "*": return primerOperando * segundoOperando;
            case "/":
                if (segundoOperando == 0) {
                    JOptionPane.showMessageDialog(this,
                            "Division entre cero detectada.",
                            "Error semantico",
                            JOptionPane.WARNING_MESSAGE);
                    return 0;
                }
                return primerOperando / segundoOperando;
            case "^": return Math.pow(primerOperando, segundoOperando);
            default: return 0;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Frrameinterfaz().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNotacionPolaca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea jTextInOrden;
    private javax.swing.JTextArea jTextPostOrden;
    private javax.swing.JTextArea jTextPreOrden;
    private javax.swing.JTextArea jTextReglasSemanticas;
    private javax.swing.JTextArea jTextTresDirecciones;
    // End of variables declaration//GEN-END:variables
}
